
name: Push Changes on Success

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installations
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Checkout Friend's Repository
      uses: actions/checkout@v2
      with:
        repository: 'MZAINR/Capstone_Project'
        ref: 'main' 

    - name: Push Changes to Your Repository
      if: success()
      run: |
          git config --global user.email "zainrizqulloh@gmail.com"
          git config --global user.name "MZAINR"
          git pull other_repo main