name: Push Changes to Main on Success

on:
  push:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installations
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Create Pull Request
      if: success()
      run: |
          git config user.name "MZAINR"
          git config user.email "zainrizqulloh@gmail.com"
          git checkout -b dev-to-main
          git add .
          git commit -m "Linted and tested changes"
          git push origin dev-to-main

  merge-to-main:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge to Main
      run: |
          git config user.name "MZAINR"
          git config user.email "zainrizqulloh@gmail.com"
          git checkout main
          git pull origin dev-to-main
          git push origin main
