name: Push Changes on Success

on:
  push:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installations
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Push Changes to other Repository
      if: success()
      run: |
          git config user.name "MZAINR"
          git config user.email "zainrizqulloh@gmail.com"
          git push origin dev:main
