name: Git Branch -r Example

on:
  push:
    branches:
      - main
      - dev

jobs:
  git_branch_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Remote Branches
        run: |
          git fetch --prune --tags
          git branch -r