name: ESLint Check and Auto-Merge

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

  auto-merge:
    runs-on: ubuntu-latest
    needs: lint
    if: success() # Tambahkan kondisi ini
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      run: git merge origin/dev --no-ff --no-commit
      env:
        GITHUB_TOKEN: ${{ secrets.COBA }}

    - name: Push to main
      run: |
        git commit -m "{now}"

        git config --global user.email "zainrizqulloh@gmail.com"
        git config --global user.name "MZAINR"

        git push origin main
        