name: ESLint Check and Auto-Merge

on:
  push:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Friend's Repository
      uses: actions/checkout@v2
      with:
        repository: 'MZAINR-PROJECTS/CICD'
        ref: 'main' # Ganti dengan branch yang diinginkan

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

  auto-merge:
    runs-on: ubuntu-latest
    needs: lint
    if: success() 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      run: |
        git fetch --prune --tags
        git branch -r
        git checkout main
        git merge --allow-unrelated-histories dev
        git commit -m "push production"
        git push
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

      env:
        GITHUB_TOKEN: ${{ secrets.COBA }}

        
        