name: ESLint Check and Auto-Merge

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Friend's Repository
      uses: actions/checkout@v2
      with:
        repository: 'MZAINR-PROJECTS/CICD'
        ref: 'main' # Ganti dengan branch yang diinginkann

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

  auto-merge:
    runs-on: ubuntu-latest
    needs: lint
    if: success() 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git Identity
      run: |
        git config user.email "zainrizqulloh@gmail.com"
        git config user.name "MZAINR"
      env:
        GITHUB_TOKEN: ${{ secrets.COBA }}

    - name: Perform Git Operations
      run: |
        git fetch --prune --tags
        git branch -r
        git pull
        git push origin dev:main
        git checkout main
        git pull
      env:
        GITHUB_TOKEN: ${{ secrets.COBA }}



        
        
