name: Push Changes on Success

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.COBA }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installations
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Checkout Friend's Repository
      uses: actions/checkout@v2
      with:
        repository: 'MZAINR/Capstone_Project'
        ref: 'main' 

    - name: Push Changes to Your Repository
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.COBA }}
      run: |
          git config --global user.email "zainrizqulloh@gmail.com"
          git config --global user.name "MZAINR"
          git remote add other_repo https://github.com/MZAINR-PROJECTS/CICD.git
          git fetch other_repo
          git branch -r
          git merge other_repo/main --allow-unrelated-histories -Xtheirs
          git push origin main